### ISSUE TITLE
Update confluent.kafka to 1.9.2 to work with M1

### ISSUE THREAD

**Issue by vcheung01** [LGouellec/kafka-streams-dotnet#182]
Description
===========
Failing on Mock with confluent.kafka updated.

Running on M1. 
Streamiz.Kafka.Net nuget version: 1.3.2
confluent.kafka version: 1.9.2

Stack trace:
```
System.TypeLoadException
Method 'DeleteGroupsAsync' in type 'Streamiz.Kafka.Net.Mock.Sync.SyncAdminClient' from assembly 'Streamiz.Kafka.Net, Version=1.3.2.0, Culture=neutral, PublicKeyToken=75e24dc15437bbc5' does not have an implementation.
   at Streamiz.Kafka.Net.Mock.Sync.SyncKafkaSupplier..ctor()
   at Streamiz.Kafka.Net.Mock.TaskSynchronousTopologyDriver..ctor(String clientId, InternalTopologyBuilder topologyBuilder, IStreamConfig configuration, IStreamConfig topicConfiguration, IKafkaSupplier supplier, CancellationToken token)
   at Streamiz.Kafka.Net.Mock.TopologyTestDriver..ctor(InternalTopologyBuilder builder, IStreamConfig config, Mode mode, IKafkaSupplier supplier)
   at Streamiz.Kafka.Net.Mock.TopologyTestDriver..ctor(InternalTopologyBuilder builder, IStreamConfig config, Mode mode)
   at Streamiz.Kafka.Net.Mock.TopologyTestDriver..ctor(Topology topology, IStreamConfig config, Mode mode)
```

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] A code snippet with your topology builder (ex: builder.Stream<string, string>("topic").to("an-another-topic");)
 - [ ] Streamiz.Kafka.Net nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with in debug mode (log4net and StreamConfig.Debug) as necessary in configuration).
 - [ ] Critical issue.

**Comment by LGouellec** [comment]
This PR #169 fix this issue and will be release soon. Stay tuned ! 💥

**Comment by LGouellec** [comment]
Workaround : Downgrade Confluent.Kafka to 1.9.1

**Comment by vcheung01** [comment]
Do you have a planned release date?

**Comment by LGouellec** [comment]
Around End October / Mid November
