### ISSUE TITLE
Issue with State store / Outer join functionality 

### ISSUE THREAD

**Issue by pwoltschk** [LGouellec/kafka-streams-dotnet#306]
Description
===========
I encountered an issue while playing around with the Outer Join functionality. Also when executing the unit tests, one of the tests failed with the following error:

```
 info: Streamiz.Kafka.Net.Processors.Internal.ProcessorStateManager[0]
      State store KSTREAM-OUTERTHIS-0000000004-store did not find checkpoint offset, hence would default to the starting offset at changelog test-stream-stream-outer-join-d53bc4d2-2511-4592-a4f0-758735f0a5e6-KSTREAM-OUTERTHIS-0000000004-store-changelog [[0]]
info: Streamiz.Kafka.Net.Processors.Internal.ProcessorStateManager[0]
      State store KSTREAM-OUTEROTHER-0000000005-store did not find checkpoint offset, hence would default to the starting offset at changelog test-stream-stream-outer-join-d53bc4d2-2511-4592-a4f0-758735f0a5e6-KSTREAM-OUTEROTHER-0000000005-store-changelog [[0]]
info: Streamiz.Kafka.Net.Processors.StreamTask[0]
      stream-task[0|0] Task 0-0 state transition from CREATED to RESTORING
info: Streamiz.Kafka.Net.Processors.StreamTask[0]
      stream-task[0|0] Restoration will start soon.
info: Streamiz.Kafka.Net.Processors.StreamTask[0]
      stream-task[0|0] Task 0-0 state transition from RESTORING to RUNNING
info: Streamiz.Kafka.Net.Processors.StreamTask[0]
      stream-task[0|0] Restored and ready to run
info: Streamiz.Kafka.Net.Processors.StreamTask[0]
      stream-task[0|0] Closing
fail: Streamiz.Kafka.Net.Processors.StreamTask[0]
      stream-task[0|0] Error during flush state store with exception :
      Streamiz.Kafka.Net.Errors.InvalidStateStoreException: Store KSTREAM-OUTEROTHER-0000000005-store.1703943140000 is currently closed
         at Streamiz.Kafka.Net.State.RocksDb.RocksDbKeyValueStore.CheckStateStoreOpen() in C:\Users\wopa\Source\Repos\kafka-streams-dotnet\core\State\RocksDb\RocksDbKeyValueStore.cs:line 424
         at Streamiz.Kafka.Net.State.RocksDb.RocksDbKeyValueStore.Flush() in C:\Users\wopa\Source\Repos\kafka-streams-dotnet\core\State\RocksDb\RocksDbKeyValueStore.cs:line 203
         at Streamiz.Kafka.Net.State.Internal.AbstractSegments`1.Flush() in C:\Users\wopa\Source\Repos\kafka-streams-dotnet\core\State\Internal\AbstractSegments.cs:line 56
         at Streamiz.Kafka.Net.State.RocksDb.Internal.AbstractRocksDBSegmentedBytesStore`1.Flush() in C:\Users\wopa\Source\Repos\kafka-streams-dotnet\core\State\RocksDb\Internal\AbstractRocksDBSegmentedBytesStore.cs:line 81
         at Streamiz.Kafka.Net.State.Internal.WrappedStateStore`1.Flush() in C:\Users\wopa\Source\Repos\kafka-streams-dotnet\core\State\Internal\WrappedStateStore.cs:line 47
         at Streamiz.Kafka.Net.State.Internal.WrappedStateStore`1.Flush() in C:\Users\wopa\Source\Repos\kafka-streams-dotnet\core\State\Internal\WrappedStateStore.cs:line 47
         at Streamiz.Kafka.Net.State.Internal.WrappedStateStore`1.Flush() in C:\Users\wopa\Source\Repos\kafka-streams-dotnet\core\State\Internal\WrappedStateStore.cs:line 47
         at Streamiz.Kafka.Net.State.Metered.MeteredWindowStore`2.<Flush>b__23_0() in C:\Users\wopa\Source\Repos\kafka-streams-dotnet\core\State\Metered\MeteredWindowStore.cs:line 154
         at Streamiz.Kafka.Net.Crosscutting.ActionHelper.MeasureLatency(Action actionToMeasure, Sensor sensor) in C:\Users\wopa\Source\Repos\kafka-streams-dotnet\core\Crosscutting\ActionHelper.cs:line 27
         at Streamiz.Kafka.Net.State.Metered.MeteredWindowStore`2.Flush() in C:\Users\wopa\Source\Repos\kafka-streams-dotnet\core\State\Metered\MeteredWindowStore.cs:line 154
         at Streamiz.Kafka.Net.Processors.Internal.ProcessorStateManager.Flush() in C:\Users\wopa\Source\Repos\kafka-streams-dotnet\core\Processors\Internal\ProcessorStateManager.cs:line 96
         at Streamiz.Kafka.Net.Processors.AbstractTask.FlushState() in C:\Users\wopa\Source\Repos\kafka-streams-dotnet\core\Processors\AbstractTask.cs:line 137
```

This issue seems to be related to the state store's behavior during unit testing of the Outer Join functionality. Any assistance in resolving this would be greatly appreciated.

What I am doing wrong?

How to reproduce
================

1. Clone the kafka-streams-dotnet package from GitHub.
2. Use the Outer Join functionality.
3. Run unit tests associated with the Outer Join functionality.
4. Observe the error described above.

**Comment by LGouellec** [comment]
Hi @pwoltschk , 

Your issue is still happening or not ? because you have closed the issue ?
